export const dumaydata  = [
    { id: 1, name: 'Shop A' },
    { id: 2, name: 'Shop B' },
    { id: 3, name: 'Shop C' },
    { id: 4, name: 'Shop D' },
    { id: 5, name: 'Shop E' },
    { id: 6, name: 'Shop F' },
    { id: 7, name: 'Shop G' },
    { id: 8, name: 'Shop H' },
    { id: 9, name: 'Shop I' },
    { id: 10, name: 'Shop J' },

    { id: 11, name: 'Dhaka Mart' },
    { id: 12, name: 'Chittagong Store' },
    { id: 13, name: 'Rajshahi Traders' },
    { id: 14, name: 'Sylhet Bazar' },
    { id: 15, name: 'Khulna Stores' },
    { id: 16, name: 'Barishal Point' },
    { id: 17, name: 'Rangpur Store' },
    { id: 18, name: 'Mymensingh Super Shop' },
    { id: 19, name: 'Kurigram Enterprise' },
    { id: 20, name: 'Bogra Mart' },

    { id: 21, name: 'Narayanganj Variety Store' },
    { id: 22, name: 'Gazipur Corner Shop' },
    { id: 23, name: 'Tangail Bhandar' },
    { id: 24, name: 'Comilla General Store' },
    { id: 25, name: 'Feni Mart' },
    { id: 26, name: 'Noakhali Shop' },
    { id: 27, name: 'Cox’s Bazar Store' },
    { id: 28, name: 'Jessore Traders' },
    { id: 29, name: 'Jhenaidah Store' },
    { id: 30, name: 'Pabna Super Shop' },

    { id: 31, name: 'Sirajganj Mart' },
    { id: 32, name: 'Jamalpur Store' },
    { id: 33, name: 'Sherpur Bazar' },
    { id: 34, name: 'Habiganj General Store' },
    { id: 35, name: 'Sunamganj Shop' },
    { id: 36, name: 'Madaripur Store' },
    { id: 37, name: 'Shariatpur Bhandar' },
    { id: 38, name: 'Gopalganj Traders' },
    { id: 39, name: 'Kishoreganj Store' },
    { id: 40, name: 'Manikganj Store' },

    { id: 41, name: 'Faridpur Mart' },
    { id: 42, name: 'Lakshmipur Store' },
    { id: 43, name: 'Chandpur General Store' },
    { id: 44, name: 'Brahmanbaria Shop' },
    { id: 45, name: 'Gaibandha Store' },
    { id: 46, name: 'Dinajpur Mart' },
    { id: 47, name: 'Thakurgaon Shop' },
    { id: 48, name: 'Panchagarh Store' },
    { id: 49, name: 'Nilphamari Traders' },
    { id: 50, name: 'Lalmonirhat Store' },

    { id: 51, name: 'Meherpur Shop' },
    { id: 52, name: 'Chuadanga Mart' },
    { id: 53, name: 'Kushtia Store' },
    { id: 54, name: 'Magura General Store' },
    { id: 55, name: 'Narail Mart' },
    { id: 56, name: 'Satkhira Store' },
    { id: 57, name: 'Pirojpur Mart' },
    { id: 58, name: 'Jhalokathi Shop' },
    { id: 59, name: 'Bhola General Store' },
    { id: 60, name: 'Patuakhali Mart' },

    { id: 61, name: 'Barguna Store' },
    { id: 62, name: 'Bandarban Mart' },
    { id: 63, name: 'Rangamati Store' },
    { id: 64, name: 'Khagrachari Traders' },
    { id: 65, name: 'Munshiganj Bazar' },
    { id: 66, name: 'Netrakona Store' },
    { id: 67, name: 'Bogura Super Mart' },
    { id: 68, name: 'Chapai Nawabganj Store' },
    { id: 69, name: 'Naogaon Mart' },
    { id: 70, name: 'Joypurhat Store' },

    { id: 71, name: 'Narsingdi Store' },
    { id: 72, name: 'Moulvibazar Shop' },
    { id: 73, name: 'Gazi Super Shop' },
    { id: 74, name: 'Metro Cash & Carry' },
    { id: 75, name: 'City Mart' },
    { id: 76, name: 'Deshi Bazar' },
    { id: 77, name: 'Family Needs Store' },
    { id: 78, name: 'Daily Fresh Mart' },
    { id: 79, name: 'Green Valley Store' },
    { id: 80, name: 'Modern Traders' },

    { id: 81, name: 'Prime Mart' },
    { id: 82, name: 'Quality Store' },
    { id: 83, name: 'Local Bazar' },
    { id: 84, name: 'Mini Market' },
    { id: 85, name: 'New Line Store' },
    { id: 86, name: 'Kazi General Store' },
    { id: 87, name: 'Amin Traders' },
    { id: 88, name: 'Bhai Bhai Store' },
    { id: 89, name: 'Super Discount Mart' },
    { id: 90, name: 'Daily Needs Store' },

    { id: 91, name: 'Market Point' },
    { id: 92, name: 'Bismillah Store' },
    { id: 93, name: 'Al Madina Mart' },
    { id: 94, name: 'Rupali Store' },
    { id: 95, name: 'Golden Mart' },
    { id: 96, name: 'Bangla Store' },
    { id: 97, name: 'National Mart' },
    { id: 98, name: 'Popular Store' },
    { id: 99, name: 'People’s Market' },
    { id: 100, name: 'Shop BD' }
];
